import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="hero-container">
        <h2 className="hero glitch layers" data-text="impwng.eth">
          <span>impwng.eth</span>
        </h2>
      </div>
    </div>
  )
}
